### ISSUE TITLE
Included Name of location when match found in Get-Places

### ISSUE THREAD

**Issue by ssabel** [45413/psGoogleMaps#1]
Currently Get-Places only returns the query string and matching address but google API  results also included the business name of the matched location. Can this be added to the results.

**Comment by 45413** [comment]
This should be an easy fix. Let me take a look.

**Comment by 45413** [comment]
This was resolved in commit [0a1936df77e](https://github.com/45413/psGoogleMaps/commit/0a1936df77e921f67e0fa35072c9e9076d70916e)
